# Build stage - generate a light-weight node image to build the project within

FROM node:lts-alpine AS build

WORKDIR /app

COPY package.json ./ 

RUN npm install

COPY . .

RUN npm run build:prod


# Deploy stage - generate a barebones nginx image configured to run a single page application

FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80